SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS Country;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE IF NOT EXISTS Country (
    name VARCHAR(64) PRIMARY KEY,
    team_initials CHAR(3) NOT NULL UNIQUE
) ENGINE=INNODB;